config/routes.rb
ResqueManager::Engine.routes.draw do

  root to: "resque#overview"

  resource 'resque', only: [:index], path: '', controller: 'resque' do
    get :overview
    get :workers
    get :working
    get :queues
    get :poll
    get :stats
    get :status_poll
    delete :remove_job
    delete :stop_worker
    put :pause_worker
    put :continue_worker
    put :restart_worker
    post :start_worker
    get :status_poll
    get :schedule
    put :schedule_requeue
    post :add_scheduled_job
    delete :remove_from_schedule
    post :start_scheduler
    delete :stop_scheduler
    delete :clear_statuses
    get :statuses
    get :status
    delete :kill
    get :cleaner
    get :cleaner_list
    post :cleaner_exec
    post :cleaner_dump
    post :cleaner_stale
  end
end

app/models/resque_manager/paginate.rb
module ResqueManager
  # Paginate class used by resque-cleaner

  #Pagination helper for list page.
  class Paginate
    attr_accessor :page_size, :page, :jobs, :url

    def initialize(jobs, url, page=1, page_size=20)
      @jobs = jobs
      @url = url
      @page = (!page || page < 1) ? 1 : page
      @page_size = 20
    end

    def first_index
      @page_size * (@page-1)
    end

    def last_index
      last = first_index + @page_size - 1
      last > @jobs.size-1 ? @jobs.size-1 : last
    end

    def paginated_jobs
      @jobs[first_index, @page_size]
    end

    def first_page?
      @page <= 1
    end

    def last_page?
      @page >= max_page
    end

    def page_url(page)
      u = @url
      u += @url.include?("?") ? "&" : "?"
      if page.is_a?(Symbol)
        page = @page - 1 if page==:prev
        page = @page + 1 if page==:next
      end
      u += "p=#{page}"
    end

    def total_size
      @jobs.size
    end

    def max_page
      ((total_size-1) / @page_size) + 1
    end
  end
end

app/controllers/resque_manager/resque_controller.rb
# Only load this file if it's running from the server, not from a rake task starting a worker.  Workers don't need the controller.
unless defined?($rails_rake_task) && $rails_rake_task
  require 'resque'
  require 'resque/version'
  require 'digest/sha1'


  module ResqueManager
    class ResqueController < ApplicationController
      unloadable(self) #needed to prevent errors with authenticated system in dev env.

      layout 'resque_manager/application'

      before_filter :check_connection

      before_filter :get_cleaner, :only => [:cleaner, :cleaner_exec, :cleaner_list, :cleaner_stale, :cleaner_dump]

      def working
        render('_working')
      end

      def queues
        render('_queues', :locals => {:partial => nil})
      end

      def poll
        @polling = true
        render(:text => (render_to_string(:action => "#{params[:page]}", :formats => [:html], :layout => false, :resque => Resque)).gsub(/\s{1,}/, ' '))
      end

      def status_poll
        @polling = true

        @start = params[:start].to_i
        @end = @start + (params[:per_page] || 20)
        @statuses = Resque::Plugins::Status::Hash.statuses(@start, @end) rescue []
        @size = Resque::Plugins::Status::Hash.status_ids.size

        render(:text => (render_to_string(:action => 'statuses', :formats => [:html], :layout => false)))
      end

      def remove_job
        # We can only dequeue a job when that job is in the same application as the UI.
        # Otherwise we get an error when we try to constantize a class that does not exist
        # in the application the UI is in.
        if ResqueManager.applications.blank?
          Resque.dequeue(params['class'].constantize, *Resque.decode(params['args']))
        end
        redirect_to request.referrer
      end

      def stop_worker
        worker = find_worker(params[:worker])
        worker.quit if worker
        redirect_to workers_resque_path
      end

      def pause_worker
        worker = find_worker(params[:worker])
        worker.pause if worker
        redirect_to workers_resque_path
      end

      def continue_worker
        worker = find_worker(params[:worker])
        worker.continue if worker
        redirect_to workers_resque_path
      end

      def restart_worker
        worker = find_worker(params[:worker])
        worker.restart if worker
        redirect_to workers_resque_path
      end

      def start_worker
        Resque::Worker.start(params)
        redirect_to workers_resque_path
      end

      def stats
        unless params[:id]
          redirect_to(stats_resque_path(:id => 'resque'))
        end

        if params[:id] == 'txt'
          info = Resque.info

          stats = []
          stats << "resque.pending=#{info[:pending]}"
          stats << "resque.processed+=#{info[:processed]}"
          stats << "resque.failed+=#{info[:failed]}"
          stats << "resque.workers=#{info[:workers]}"
          stats << "resque.working=#{info[:working]}"
          Resque.queues.each do |queue|
            stats << "queues.#{queue}=#{Resque.size(queue)}"
          end

          render(:text => stats.join("</br>").html_safe)
        end
      end

      # resque-scheduler actions

      def schedule
        @farm_status = ResqueScheduler.farm_status
      end

      def schedule_requeue
        config = Resque.schedule[params['job_name']]
        Resque::Scheduler.enqueue_from_config(config)
        redirect_to overview_resque_path
      end

      def add_scheduled_job
        errors = []
        if Resque.schedule.keys.include?(params[:name])
          errors << 'Name already exists.'
        end
        if params[:ip].blank?
          errors << 'You must enter an ip address for the server you want this job to run on.'
        end
        if params[:cron].blank?
          errors << 'You must enter the cron schedule.'
        end
        if errors.blank?
          config = {params['name'] => {'class' => params['class'],
                                       'ip' => params['ip'],
                                       'cron' => params['cron'],
                                       'args' => Resque.decode(params['args'].blank? ? nil : params['args']),
                                       'description' => params['description']}
          }
          Resque.redis.rpush(:scheduled, Resque.encode(config))
          ResqueScheduler.restart(params['ip'])
        else
          flash[:error] = errors.join('<br>').html_safe
        end
        redirect_to schedule_resque_path
      end

      def remove_from_schedule
        Resque.list_range(:scheduled, 0, -0).each do |s|
          if s[params['job_name']]
            Resque.redis.lrem(:scheduled, 0, s.to_json)
            # Restart the scheduler on the server that has changed it's schedule
            ResqueScheduler.restart(params['ip'])
          end
        end
        redirect_to schedule_resque_path
      end

      def start_scheduler
        ResqueScheduler.start(params[:ip])
        redirect_to schedule_resque_path
      end

      def stop_scheduler
        ResqueScheduler.quit(params[:ip])
        redirect_to schedule_resque_path
      end

      # resque-status actions

      def statuses
        @start = params[:start].to_i
        @end = @start + (params[:per_page] || 20)
        @statuses = Resque::Plugins::Status::Hash.statuses(@start, @end)
        @size = Resque::Plugins::Status::Hash.status_ids.size
        respond_to do |format|
          format.js { render json: @statuses }
          format.html { render :statuses }
        end
      end

      def clear_statuses
        Resque::Plugins::Status::Hash.clear
        redirect_to statuses_resque_path
      end

      def status
        @status = Resque::Plugins::Status::Hash.get(params[:uuid])
        respond_to do |format|
          format.js { render json: @status }
          format.html { render :status }
        end
      end

      def kill
        Resque::Plugins::Status::Hash.kill(params[:uuid])
        s = Resque::Plugins::Status::Hash.get(params[:uuid])
        s.status = 'killed'
        Resque::Plugins::Status::Hash.set(params[:uuid], s)
        redirect_to statuses_resque_path
      end

      def cleaner
        load_cleaner_filter

        @jobs = @cleaner.select
        @stats, @total = {}, {"total" => 0, "1h" => 0, "3h" => 0, "1d" => 0, "3d" => 0, "7d" => 0}
        @jobs.each do |job|
          klass = job["payload"]["class"]
          failed_at = Time.parse job["failed_at"]

          @stats[klass] ||= {"total" => 0, "1h" => 0, "3h" => 0, "1d" => 0, "3d" => 0, "7d" => 0}
          items = [@stats[klass], @total]

          items.each { |a| a["total"] += 1 }
          items.each { |a| a["1h"] += 1 } if failed_at >= hours_ago(1)
          items.each { |a| a["3h"] += 1 } if failed_at >= hours_ago(3)
          items.each { |a| a["1d"] += 1 } if failed_at >= hours_ago(24)
          items.each { |a| a["3d"] += 1 } if failed_at >= hours_ago(24*3)
          items.each { |a| a["7d"] += 1 } if failed_at >= hours_ago(24*7)
        end
      end

      def cleaner_list
        load_cleaner_filter

        block = filter_block

        @failed = @cleaner.select(&block).reverse

        url = "cleaner_list?c=#{@klass}&ex=#{@exception}&f=#{@from}&t=#{@to}"
        @dump_url = "cleaner_dump?c=#{@klass}&ex=#{@exception}&f=#{@from}&t=#{@to}"
        @paginate = ResqueManager::Paginate.new(@failed, url, params[:p].to_i)

        @klasses = @cleaner.stats_by_class.keys
        @exceptions = @cleaner.stats_by_exception.keys
        @count = @cleaner.select(&block).size
      end

      def cleaner_exec
        load_cleaner_filter

        if params[:select_all_pages]!="1"
          @sha1 = {}
          params[:sha1].split(",").each { |s| @sha1[s] = true }
        end

        block = filter_block

        @count =
            case params[:form_action]
              when "clear" then
                @cleaner.clear(&block)
              when "retry_and_clear" then
                @cleaner.requeue(true, &block)
              when "retry" then
                @cleaner.requeue(false, {}, &block)
            end

        @link_url = "cleaner_list?c=#{@klass}&ex=#{@exception}&f=#{@from}&t=#{@to}"
      end

      def cleaner_dump
        load_cleaner_filter

        block = filter_block
        failures = @cleaner.select(&block)
        # pretty generate throws an error with the json gem on jruby
        output = JSON.pretty_generate(failures) rescue failures.to_json
        render :json => output
      end

      def cleaner_stale
        @cleaner.clear_stale
        redirect_to cleaner_resque_path
      end


      private

      def check_connection
        Resque.keys
      rescue Errno::ECONNREFUSED
        render(:template => 'resque_manager/resque/error', :layout => false, :locals => {:error => "Can't connect to Redis! (#{Resque.redis_id})"})
        false
      end

      def find_worker(worker)
        return nil if worker.blank?
        worker = CGI::unescape(worker)
        first_part, *rest = worker.split(':')
        first_part.gsub!(/_/, '.')
        Resque::Worker.find("#{first_part}:#{rest.join(':')}")
      end

      # resque-cleaner methods

      def get_cleaner
        @cleaner ||= Resque::Plugins::ResqueCleaner.new
        @cleaner.print_message = false
        @cleaner
      end

      def load_cleaner_filter
        @from = params[:f].blank? ? nil : params[:f]
        @to = params[:t].blank? ? nil : params[:t]
        @klass = params[:c].blank? ? nil : params[:c]
        @exception = params[:ex].blank? ? nil : params[:ex]
      end

      def filter_block
        lambda { |j|
          (!@from || j.after?(hours_ago(@from))) &&
              (!@to || j.before?(hours_ago(@to))) &&
              (!@klass || j.klass?(@klass)) &&
              (!@exception || j.exception?(@exception)) &&
              (!@sha1 || @sha1[Digest::SHA1.hexdigest(j.to_json)])
        }
      end

      def hours_ago(h)

app/helpers/resque_manager/application_helper.rb
module ResqueManager
  module ApplicationHelper
  end
end

app/helpers/resque_manager/resque_helper.rb
module ResqueManager
  module ResqueHelper

    def flash_helper
      [:notice, :warning, :message, :error].collect do |key|
        content_tag(:div, flash[key], :class => "flash #{key}") unless flash[key].blank?
      end.join
    end

    def format_time(t)
      t.strftime("%Y/%m/%d %H:%M:%S %Z")
    end

    def current_section
      (request.path_info.sub('/', '').split('/').first || 'overview').downcase
    end

    def current_page
      url request.path_info.sub('/', '').downcase
    end

    def url(*path_parts)
      [path_prefix, path_parts].join("/").squeeze('/')
    end

    alias_method :u, :url

    def path_prefix
      request.env['SCRIPT_NAME']
    end

    def class_if_current(page = '')
      'class="current"' if current_page.include? page.to_s
    end

    def tab(name)
      dname = "#{name.to_s.downcase}"
      "<li #{class_if_current(dname)}>#{link_to(name, url(dname))}</li>".html_safe
    end

    def find_worker(worker)
      first_part, *rest = worker.split(':')
      first_part.gsub!(/_/, '.')
      Resque::Worker.find("#{first_part}:#{rest.join(':')}")
    end

    def redis_get_size(key)
      case Resque.redis.type(key)
        when 'none'
          []
        when 'list'
          Resque.redis.llen(key)
        when 'set'
          Resque.redis.scard(key)
        when 'string'
          Resque.redis.get(key).length
      end
    end

    def redis_get_value_as_array(key)
      case Resque.redis.type(key)
        when 'none'
          []
        when 'list'
          Resque.list_range(key, 0, 20)
        when 'set'
          Resque.redis.smembers(key)
        when 'string'
          [Resque.redis.get(key)]
      end
    end

    def show_args(args)
      Array(args).map { |a| a.inspect }.join("\n")
    end

    def partial?
      @partial
    end

    def poll
      if @polling
        text = "Last Updated: #{Time.now.strftime("%H:%M:%S")}"
      else
        text = link_to('Live Poll', poll_resque_path(page: current_section), :rel => 'poll')
      end
      "<p class='poll'>#{text}</p>".html_safe
    end

    def status_poll(start)
      if @polling
        text = "Last Updated: #{Time.now.strftime("%H:%M:%S")}"
      else
        text = link_to('Live Poll', status_poll_resque_path({:start => start}), :rel => 'poll')
      end
      "<p class='poll'>#{text}</p>".html_safe
    end

    def resque
      Resque
    end

    # resque-cleaner helpers

    def time_filter(id, name, value)
      html = "<select id=\"#{id}\" name=\"#{name}\">"
      html += "<option value=\"\">-</option>"
      [1, 3, 6, 12, 24].each do |h|
        selected = h.to_s == value ? 'selected="selected"' : ''
        html += "<option #{selected} value=\"#{h}\">#{h} #{h==1 ? "hour" : "hours"} ago</option>"
      end
      [3, 7, 14, 28].each do |d|
        selected = (d*24).to_s == value ? 'selected="selected"' : ''
        html += "<option #{selected} value=\"#{d*24}\">#{d} days ago</option>"
      end
      html += "</select>"
      html.html_safe
    end

    def class_filter(id, name, klasses, value)
      html = "<select id=\"#{id}\" name=\"#{name}\">"
      html += "<option value=\"\">-</option>"
      klasses.each do |k|
        selected = k == value ? 'selected="selected"' : ''
        html += "<option #{selected} value=\"#{k}\">#{k}</option>"
      end
      html += "</select>"
      html.html_safe
    end

    def exception_filter(id, name, exceptions, value)
      html = "<select id=\"#{id}\" name=\"#{name}\">"
      html += "<option value=\"\">-</option>"
      exceptions.each do |ex|
        selected = ex == value ? 'selected="selected"' : ''
        html += "<option #{selected} value=\"#{ex}\">#{ex}</option>"
      end
      html += "</select>"
      html.html_safe
    end
  end
end

app/views/resque_manager/resque/_queues.html.erb
<% @partial ||= partial -%>

<% @subtabs = resque.queues unless partial? %>

<% if queue = params[:id] %>

    <h1>Pending jobs on <span class='hl'><%= queue %></span></h1>
    <p class='sub'>Showing <%= start = params[:start].to_i %> to <%= start + 20 %> of
      <b><%= size = resque.size(queue) %></b> jobs</p>
    <table class='jobs'>
      <tr>
        <th>Class</th>
        <th>Args</th>
        <% if ResqueManager.applications.blank? %>
            <th>&nbsp;</th>
        <% end %>
      </tr>
      <% for job in (jobs = resque.peek(queue, start, 20)) %>
          <tr>
            <td class='class'><%= job['class'] %></td>
            <td class='args'><%= job['args'].inspect.html_safe %></td>
            <% if ResqueManager.applications.blank? %>
                <td>
                  <%= button_to "Remove", remove_job_resque_path(class: job['class'], args: Resque.encode(job['args'])), :class => 'clear-failed', :method => :delete %>
                </td>
            <% end %>
          </tr>
      <% end %>
      <% if jobs.empty? %>
          <tr>
            <td class='no-data' colspan='3'>There are no pending jobs in this queue</td>
          </tr>
      <% end %>
    </table>
    <%= render(:partial => 'next_more', :locals => {:start => start, :size => size}) %>
<% else %>

    <h1 class='wi'>Queues</h1>

    <p class='intro'>The list below contains all the registered queues with the number of jobs currently in the
      queue. Select a queue from above to view all jobs currently pending on the queue.</p>
    <table class='queues'>
      <tr>
        <th>Name</th>
        <th>Jobs</th>
      </tr>
      <% for queue in resque.queues.sort_by { |q| q.to_s } %>
          <tr>
            <td class='queue'><%= link_to(queue, queues_resque_path(id: queue), :class => 'queue') %></td>
            <td class='size'><%= resque.size queue %></td>
          </tr>
      <% end %>
      <tr class='failed'>
        <td class='queue failed'><%= link_to('failed', cleaner_resque_path , :class => 'queue') %></td>
        <td class='size'><%= Resque::Failure.count %></td>
      </tr>
    </table>

<% end %>

app/views/resque_manager/resque/_workers.html.erb
<% if params[:id] && worker = find_worker(params[:id]) %>

    <h1>Worker <%= worker %></h1>
    <table class='workers'>
      <tr>
        <th>&nbsp;</th>
        <th>Host</th>
        <th>Path</th>
        <th>Pid</th>
        <th>Thread</th>
        <th>Started</th>
        <th>Paused</th>
        <th>Queues</th>
        <th>Processed</th>
        <th>Failed</th>
        <th>Processing</th>
      </tr>
      <tr>
        <td class='icon'>
          <img src="<%= "/assets/resque_manager/#{state = worker.state}" %>.png" alt="<%= state %>" title="<%= state %>">
        </td>

        <% host, pid, thread, path, queues = worker.to_s.split(':') %>
        <td><%= host %></td>
        <td><%= path %></td>
        <td><%= pid %></td>
        <td><%= thread %></td>
        <td><span class="time"><%= format_time(Time.zone.parse(worker.started)) %></span></td>
        <td>
          <% if worker.paused? %>
              <span class="time"><%= format_time(Time.zone.parse(worker.paused)) %></span>
        <% else %>
              <span>Not Paused</span>
        <% end %>
        </td>
        <td class='queues'><%= queues.split(',').map { |q| link_to(q, queues_resque_path(id: q), :class => 'queue-tag') }.join('').html_safe %></td>
        <td><%= worker.processed %></td>
        <td><%= worker.failed %></td>
        <td class='process'>
          <% data = worker.processing || {} %>
          <% if data['queue'] %>
              <code><%= data['payload']['class'] %></code>
              <small><%= link_to(format_time(Time.zone.parse(data['run_at'])), working_resque_path(id: worker.to_s.gsub(/\./, '_')), :class => "queue time") %></small>
              <br>
              <small><%= worker.overview_message %></small>
          <% else %>
              <span class='waiting'>Waiting for a job...</span>
          <% end %>
        </td>
      </tr>
    </table>

<% elsif params[:id] %>

    <h1>Worker doesn't exist</h1>

<% else %>

    <h1 class='wi'><%= pluralize resque.workers.size, 'Worker' %></h1>
    <p class='intro'>The workers listed below are all registered as active on your system.</p>
    <table class='workers'>
      <tr>
        <th>&nbsp;</th>
        <th>Where (ip):pid:thread:path</th>
        <th>Queues</th>
        <th>Processing</th>
        <th>&nbsp;</th>
      </tr>
      <% upid = '' %>
      <% for worker in (workers = resque.workers.sort_by { |w| w.to_s }) %>
          <tr class="<%= state = worker.state %>">
            <td class='icon'>
              <img src="<%="/assets/resque_manager/#{state}" %>.png" alt="<%= state %>" title="<%= state %>"></td>

            <% host, pid, thread, path, queues = worker.to_s.split(':') %>
            <td class='where'><%= link_to("#{host}:#{pid}:#{thread}:#{path}", workers_resque_path(id: worker.to_s.gsub(/\./, '_'))) %></td>
            <td class='queues'><%= queues.split(',').map { |q| link_to(q, queues_resque_path(id: q), :class => 'queue-tag') }.join('').html_safe %></td>

            <td class='process'>
              <% data = worker.processing || {} %>
              <% if data['queue'] %>
                  <code><%= data['payload']['class'] %></code>
                  <small><%= link_to(format_time(Time.zone.parse(data['run_at'])), working_resque_path(id: worker.to_s.gsub(/\./, '_')), :class => "queue time") %></small>
                  <br/>
                  <small><%= worker.overview_message %></small>
              <% else %>
                  <span class='waiting'>Waiting for a job...</span>
              <% end %>
            </td>
            <td>
              <% if upid != pid %>
                  <%= button_to "Stop", stop_worker_resque_path(worker: worker.to_s), :class => 'clear-failed', method: :delete, :title => "This will stop all workers on #{host} in pid #{pid}: #{worker.workers_in_pid.collect { |w| w.to_s }.join(', ')}" %>
                  <% if worker.paused? %>
                      <%= button_to "Unpause", continue_worker_resque_path(worker: worker.to_s), :class => 'clear-failed', method: :put, :title => "This will unpause all workers on #{host} in pid #{pid}: #{worker.workers_in_pid.collect { |w| w.to_s }.join(', ')}" %>
                  <% else %>
                      <%= button_to "Pause", pause_worker_resque_path(worker: worker.to_s), :class => 'clear-failed', method: :put, :title => "This will pause all workers on #{host} in pid #{pid}: #{worker.workers_in_pid.collect { |w| w.to_s }.join(', ')}" %>
                  <% end %>
                  <%= button_to "Restart", restart_worker_resque_path(worker: worker.to_s), :class => 'clear-failed', method: :put, :title => "This will restart all workers on #{host} in pid #{pid}: #{worker.workers_in_pid.collect { |w| w.to_s }.join(', ')}" %>
                  <% upid = pid %>
              <% end %>
            </td>
          </tr>
      <% end %>
      <% if workers.empty? %>
          <tr>
            <td colspan='5' class='no-data'>There are no registered workers</td>
          </tr>
      <% end %>
    </table>
    <%= poll %>
    <br/>
    <hr/>
    <h1 class='wi'>Start New Workers</h1>
    <%= form_tag :action => 'start_worker' do -%>
        <ul class='new_worker'>
          <li>
            <dl>
              <dt>Queue(s)</dt>
              <dd><%= text_field_tag :queues, nil, :size => 125 %>
                <br/> Prefix each worker with a '#', comma separate the list of queues you want each worker to monitor.
                No Spaces. #queue1,queue2#queue3#queue2 will produce 3 workers in 3 threads.
              </dd>
              <dt>Host(s)/IP(s)</dt>
              <dd><%= text_field_tag :hosts, nil, :size => 125 %>
                <br/> Comma separate the IP address of the servers where you want your worker to run.
              </dd>
              <% if ResqueManager.applications.present? %>
                  <dt>Application</dt>
                  <dd><%= select_tag :application_path, options_for_select(ResqueManager.applications.to_a), :include_blank => true %>
                    <br/> The application where the workers are if not in the same application as the UI.
                  </dd>
              <% end %>
              <dt><%= submit_tag "Start", :id => "submit" %></dt>
            </dl>
          </li>
        </ul>
    <% end -%>
<% end %>

app/views/resque_manager/resque/cleaner_exec.html.erb
<div class="cleaner">
  <p class="message">Processed <%= @count %> jobs.</p>
  <p class="back_to_list">
  <a href="<%=@link_url%>">Back to List</a>
  </p>
</div>

app/views/resque_manager/resque/delayed.html.erb
<h1>Delayed Jobs</h1>

<p class='intro'>
  This list below contains the timestamps for scheduled delayed jobs.
</p>

<p class='sub'>
  Showing <%= start = params[:start].to_i %> to <%= start + 20 %> of <b><%=size = resque.delayed_queue_schedule_size %></b> timestamps
</p>

<table>
  <tr>
    <th>Timestamp</th>
    <th>Job count</th>
    <th>Class</th>
    <th>Args</th>
  </tr>
  <% resque.delayed_queue_peek(start, start+20).each do |timestamp| %>
    <tr>
      <td><a href="<%= url "delayed/#{timestamp}" %>"><%= format_time(Time.at(timestamp)) %></a></td>
      <td><%= delayed_timestamp_size = resque.delayed_timestamp_size(timestamp) %></td>
      <% job = resque.delayed_timestamp_peek(timestamp, 0, 1).first %>
      <td>
        <% if job && delayed_timestamp_size == 1 %>
          <%= h(job['class']) %>
        <% else %>
          <a href="<%= url "delayed/#{timestamp}" %>">see details</a>
        <% end %>
      </td>
      <td><%= h(job['args'].inspect) if job && delayed_timestamp_size == 1 %></td>
    </tr>
  <% end %>
</table>

<%= render(:partial => 'next_more', :locals => {:start => start, :size => size}) %>

app/views/resque_manager/resque/schedule.html.erb
<div id="schedule">
  <h1>Schedule</h1>

  <p class='intro'>
    The list below contains all scheduled jobs.  Click &quot;Queue now&quot; to queue
    a job immediately.
  </p>

  <table>
    <tr>
      <th></th>
      <th>Name</th>
      <th>IP</th>
      <th>Description</th>
      <th>Cron</th>
      <th>Class</th>
      <th>Arguments</th>
      <th></th>
    </tr>
    <% Resque.schedule.each do |name,config| %>
      <tr>
        <td>
          <%= button_to "Queue now", schedule_requeue_resque_path(job_name: name), :method => :put %>
        </td>
        <td><%= h name %></td>
        <td><%= h config['ip'] %></td>
        <td><%= h config['description'] %></td>
        <td style="white-space:nowrap"><%= h config['cron'] %></td>
        <td><%= h config['class'] %></td>
        <td><%= h config['args'].inspect %></td>
        <td><%= button_to "Remove", remove_from_schedule_resque_path(job: name, ip: config['ip']), :method => :delete %></td>
      </tr>
    <%end%>
  </table>

  <h1>Add Job to Schedule</h1>
  <div id='flash' class="flash">
    <%flash_message = flash_helper%>
    <% unless flash_message.blank? -%>
        <%= flash_message.html_safe %>
        <%= javascript_tag "$('flash').show();" %>
    <% end %>
  </div>
  <%= form_tag '/resque/add_scheduled_job' do -%>
    <table>
      <tr>
        <th>Name</th>
        <th>IP</th>
        <th>Description</th>
        <th>Cron</th>
        <th>Class</th>
        <th>Arguments</th>
        <th></th>
      </tr>
      <tr>
        <td><%= text_field_tag :name %></td>
        <td><%= text_field_tag :ip %></td>
        <td><%= text_field_tag :description %></td>
        <td style="white-space:nowrap"><%= text_field_tag :cron %></td>
        <td><%= text_field_tag :class %></td>
        <td><%= text_area_tag :args, nil, :rows => 1, :cols => 40%></td>
        <td>
          <%= submit_tag 'Add Job', :id => 'add_job' %>
        </td>
      </tr>
    </table>
  <% end -%>

  <h1>Farm Status</h1>

  <table>
    <tr>
      <th>IP</th>
      <th>Status</th>
      <th></th>
    </tr>
    <%@farm_status.each do |ip,status| -%>
      <tr>
        <td>
          <%= ip %>
        </td>
        <td><%= status %></td>
        <td>
          <%  if status == 'Running' -%>
            <%= button_to 'Stop Scheduler', stop_scheduler_resque_path(ip: ip), :method => :delete %>
          <% else -%>
            <%= button_to 'Start Scheduler', start_scheduler_resque_path(ip: ip), :method => :post %>
          <% end -%>
        </td>
      </tr>
    <% end -%>
  </table>
</div>

app/views/resque_manager/resque/workers.html.erb
<%= render(:partial => 'workers') %>